export const aisleRef = {
  Meat: 'Meat & Fish',
  Seafood: 'Meat & Fish',
  'Milk, Eggs, Other Dairy': 'Dairy',
  Cheese: 'Dairy',
  Produce: 'Fruit & Veg',
  'Frozen;Meat': 'Frozen',
  'Produce;Ethnic Foods;Spices and Seasonings': 'Fruit & Veg',
  'Produce;Spices and Seasonings': 'Fruit & Veg',
  'Pasta and Rice': 'Pasta & Rice',
  'Ethnic Foods': 'World Foods',
  'Produce;Ethnic Foods': 'World Foods',
  'Ethnic Foods;Oil, Vinegar, Salad Dressing': 'World Foods',
  'Ethnic Foods;Condiments': 'World Foods',
  'Ethnic Foods;Spices and Seasonings': 'Spices',
  'Spices and Seasonings': 'Spices',
  'Oil, Vinegar, Salad Dressing': 'Oils & Dressings',
  'Nut butters, Jams, and Honey': 'Jams, Honey & Spreads',
  'Canned and Jarred': 'Canned Goods',
  'Canned and Jarred;Milk, Eggs, Other Dairy': 'Canned Goods',
  Beverages: 'Drinks',
  'Alcoholic Beverages': 'Drinks (Alcoholic)',
  '?': 'Other',
};
